/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.view;

import br.com.controller.Votacao;
import javax.swing.JOptionPane;

/**
 *
 * @author Alexm
 */
public class Tela extends javax.swing.JFrame {
    Votacao v = new Votacao();
    /**
     * Creates new form Tela
     */
    public Tela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jRvotar1 = new javax.swing.JRadioButton();
        jRvotar2 = new javax.swing.JRadioButton();
        jBcalcularVoto = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTmatricula = new javax.swing.JTextField();
        jBfinalizar = new javax.swing.JButton();
        jLresultvotosJava = new javax.swing.JLabel();
        jLresultvotosC = new javax.swing.JLabel();
        jLmaisvotos = new javax.swing.JLabel();
        jLqtdfunc = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("VOTAÇÃO");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/view/1672309.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Escolha a melhor linguagem para trabalhar");

        jRvotar1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jRvotar1.setText("JAVA");

        jRvotar2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jRvotar2.setText("C");

        jBcalcularVoto.setBackground(new java.awt.Color(204, 0, 0));
        jBcalcularVoto.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jBcalcularVoto.setForeground(new java.awt.Color(255, 255, 255));
        jBcalcularVoto.setText("VOTAR");
        jBcalcularVoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcalcularVotoActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Digite o seu CPF para votar: ");

        jBfinalizar.setBackground(new java.awt.Color(0, 204, 0));
        jBfinalizar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jBfinalizar.setForeground(new java.awt.Color(255, 255, 255));
        jBfinalizar.setText("FINALIZAR A VOTAÇÃO");
        jBfinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBfinalizarActionPerformed(evt);
            }
        });

        jLresultvotosJava.setText("Quantidade de votos em (JAVA): ");

        jLresultvotosC.setText("Quantidade de votos em (C): ");

        jLmaisvotos.setText("Opção com mais votos: ");

        jLqtdfunc.setText("Quantidade de funcionários que votaram: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(254, 254, 254)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRvotar1)
                            .addComponent(jRvotar2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jBfinalizar)
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLresultvotosJava)
                            .addComponent(jLresultvotosC)
                            .addComponent(jLmaisvotos)
                            .addComponent(jLqtdfunc)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTmatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(41, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(125, 125, 125))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jBcalcularVoto)
                        .addGap(210, 210, 210))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTmatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jRvotar1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRvotar2)
                .addGap(18, 18, 18)
                .addComponent(jBcalcularVoto)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLresultvotosJava)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLresultvotosC)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLmaisvotos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLqtdfunc))
                    .addComponent(jBfinalizar))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBcalcularVotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcalcularVotoActionPerformed
        // TODO add your handling code here:
        v.setCpf(jTmatricula.getText());
         if(jTmatricula.getText().equals("")){
             JOptionPane.showMessageDialog(rootPane, "campo obrigatorio!");
             jTmatricula.setText("");
             jTmatricula.requestFocus();
         } else {      
        jTmatricula.setText("");
        jTmatricula.requestFocus();
        if(jRvotar1.isSelected()){
            v.votar();
            JOptionPane.showMessageDialog(rootPane,"Voto registrado com sucesso!", "Confirmação", JOptionPane.INFORMATION_MESSAGE);
            jRvotar1.setSelected(false);
        }else if (jRvotar2.isSelected()){
            v.votar(v.getVotosC());
            JOptionPane.showMessageDialog(rootPane,"Voto registrado com sucesso!", "Confirmação", JOptionPane.INFORMATION_MESSAGE);
            jRvotar2.setSelected(false);
        } else {
           JOptionPane.showMessageDialog(rootPane, "É necessário votar em uma linguagem!!"); 
        }
        
      }
    }//GEN-LAST:event_jBcalcularVotoActionPerformed

    private void jBfinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBfinalizarActionPerformed
        // TODO add your handling code here:
        jLresultvotosJava.setText("Quantidade de votos em (JAVA): "+v.getVotosJava());
        jLresultvotosC.setText("Quantidade de votos em (C): "+v.getVotosC());
        if(v.getVotosJava() > v.getVotosC()){
            jLmaisvotos.setText("Opção com mais votos é JAVA com "+v.getVotosJava());
        } else jLmaisvotos.setText("Opção com mais votos é C com "+v.getVotosC());
        jLqtdfunc.setText("Quantidade de pessoas que votaram: "+(v.getVotosC()+v.getVotosJava()));
    }//GEN-LAST:event_jBfinalizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBcalcularVoto;
    private javax.swing.JButton jBfinalizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLmaisvotos;
    private javax.swing.JLabel jLqtdfunc;
    private javax.swing.JLabel jLresultvotosC;
    private javax.swing.JLabel jLresultvotosJava;
    private javax.swing.JRadioButton jRvotar1;
    private javax.swing.JRadioButton jRvotar2;
    private javax.swing.JTextField jTmatricula;
    // End of variables declaration//GEN-END:variables
}
