/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.view;

import br.com.controller.Pessoa;
import javax.swing.JOptionPane;

/**
 *
 * @author Alexm
 */
public class Tela extends javax.swing.JFrame {
    Pessoa p = new Pessoa();
    /**
     * Creates new form Tela
     */
    public Tela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTaltura = new javax.swing.JTextField();
        jTpeso = new javax.swing.JTextField();
        jBfinalizar = new javax.swing.JButton();
        jLsup50 = new javax.swing.JLabel();
        jLmedia1020 = new javax.swing.JLabel();
        jLpercentMenor40 = new javax.swing.JLabel();
        jLcontSistema = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTidade = new javax.swing.JTextField();
        jBiniciar = new javax.swing.JButton();
        jBsubmit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(102, 102, 102));
        jLabel1.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabel1.setText("PROGRAMA PARA ANALISE DE PESSOAS");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("Digite a sua idade: ");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("Digite a sua altura: ");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setText("Digite o seu peso: ");

        jBfinalizar.setBackground(new java.awt.Color(51, 153, 255));
        jBfinalizar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jBfinalizar.setForeground(new java.awt.Color(255, 255, 255));
        jBfinalizar.setText("FINALIZAR PROGRAMA");
        jBfinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBfinalizarActionPerformed(evt);
            }
        });

        jLsup50.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLsup50.setText("Pessoas com idade superior a 50 anos: ");

        jLmedia1020.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLmedia1020.setText("Média das Alturas das pessoas com idade entre 10 e 20 anos:");

        jLpercentMenor40.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLpercentMenor40.setText("Procentagem das pessoas com peso inferior a 40 quilos:");

        jLcontSistema.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLcontSistema.setText("Quantas vezes o sistema rodou:");

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/view/pessoas.png"))); // NOI18N

        jBiniciar.setBackground(new java.awt.Color(51, 153, 255));
        jBiniciar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jBiniciar.setForeground(new java.awt.Color(255, 255, 255));
        jBiniciar.setText("INICIAR PROGRAMA");
        jBiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBiniciarActionPerformed(evt);
            }
        });

        jBsubmit.setBackground(new java.awt.Color(51, 153, 255));
        jBsubmit.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jBsubmit.setForeground(new java.awt.Color(255, 255, 255));
        jBsubmit.setText("ENVIAR");
        jBsubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBsubmitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(161, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLmedia1020)
                    .addComponent(jLsup50, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLpercentMenor40, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLcontSistema, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(159, 159, 159))
            .addGroup(layout.createSequentialGroup()
                .addGap(235, 235, 235)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTidade, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTaltura, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTpeso, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(264, 264, 264)
                        .addComponent(jBiniciar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(214, 214, 214)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(310, 310, 310)
                        .addComponent(jBsubmit))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(264, 264, 264)
                        .addComponent(jBfinalizar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(218, 218, 218)
                        .addComponent(jLabel10)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jBiniciar)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3))
                    .addComponent(jTaltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTpeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBsubmit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBfinalizar)
                .addGap(18, 18, 18)
                .addComponent(jLsup50)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLmedia1020)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLpercentMenor40)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLcontSistema)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    boolean continuarRecebendo = true;
    
    private void jBfinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBfinalizarActionPerformed
        // TODO add your handling code here:
        continuarRecebendo = false;
        
        jBiniciar.setEnabled(true);
        jBsubmit.setEnabled(false);
        jBfinalizar.setEnabled(false);
                   
           jLsup50.setText("Pessoas com idade superior a 50 anos: "+p.getSup50anos());
           jLmedia1020.setText("Média das Alturas das pessoas com idade entre 10 e 20 anos: "+p.calcularMediaAltura());
           jLpercentMenor40.setText("Procentagem das pessoas com peso inferior a 40 quilos: "+(p.caluclarPercentMenor40quilos()) +"%") ;
           jLcontSistema.setText("Quantas vezes o sistema rodou: "+p.getContSistema());
          
    }//GEN-LAST:event_jBfinalizarActionPerformed

    private void jBiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBiniciarActionPerformed
        // TODO add your handling code here:
        continuarRecebendo = true;
        jBiniciar.setEnabled(false);
        jBsubmit.setEnabled(true);
        jBfinalizar.setEnabled(true);
        jTidade.requestFocus();
        
           jLsup50.setText("Pessoas com idade superior a 50 anos: ");
           jLmedia1020.setText("Média das Alturas das pessoas com idade entre 10 e 20 anos: ");
           jLpercentMenor40.setText("Procentagem das pessoas com peso inferior a 40 quilos: ");
           jLcontSistema.setText("Quantas vezes o sistema rodou: ");
    }//GEN-LAST:event_jBiniciarActionPerformed

    private void jBsubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsubmitActionPerformed
        // TODO add your handling code here:
            continuarRecebendo = true;
       
          if(jTidade.getText().equals("")){
             JOptionPane.showMessageDialog(rootPane, "campo obrigatorio!");
             jTidade.setText("");
             jTidade.requestFocus();
          } else if(jTaltura.getText().equals("")){
             JOptionPane.showMessageDialog(rootPane, "campo obrigatorio!");
             jTaltura.setText("");
             jTaltura.requestFocus();
          } else if(jTpeso.getText().equals("")){
             JOptionPane.showMessageDialog(rootPane, "campo obrigatorio!");
             jTpeso.setText("");
             jTpeso.requestFocus();
          } else      
            
        while (continuarRecebendo) {
         
            p.setIdade(Integer.parseInt(jTidade.getText()));
            p.setAltura(Double.parseDouble(jTaltura.getText()));
            p.setPeso(Double.parseDouble(jTpeso.getText()));
            
            p.addContador();
            
            jTidade.setText("");
            jTaltura.requestFocus();
            jTaltura.setText("");
            jTaltura.requestFocus();
            jTpeso.setText("");   
            jTaltura.requestFocus();
            
            
          }
    }//GEN-LAST:event_jBsubmitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBfinalizar;
    private javax.swing.JButton jBiniciar;
    private javax.swing.JButton jBsubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLcontSistema;
    private javax.swing.JLabel jLmedia1020;
    private javax.swing.JLabel jLpercentMenor40;
    private javax.swing.JLabel jLsup50;
    private javax.swing.JTextField jTaltura;
    private javax.swing.JTextField jTidade;
    private javax.swing.JTextField jTpeso;
    // End of variables declaration//GEN-END:variables
}
